# Generated by Django 4.2.16 on 2024-11-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app19', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelOptions(
            name='blog_post',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
